services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      # POSTGRES_DB: postgres
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
